- name: Deploy on server
  uses: appleboy/ssh-action@v0.1.4
  with:
    host: 54.226.150.253
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY }}
    port: 22
    script: |
      cd /home/ubuntu/app
      docker stop app || true
      docker rm app || true
      docker build -t app .
      docker run -d -p 5000:5000 --name app app
